Fix vue TypeScript declarations
RenderFunction has the wrong signature, causing

  error TS2786: '...' cannot be used as a JSX component.
    Its return type 'VNodeChild' is not a valid JSX element.
      Type 'undefined' is not assignable to type 'Element | null'.

as documented in #516.

This commit reverts 1658f7c47d883228374d4304187f179b6d29d6ef.